In [3]:
import numpy as np
from multiprocessing import shared_memory

In [4]:
a = np.array([1, 1, 2, 3, 5, 8])  # Start with an existing NumPy array

In [7]:
shm = shared_memory.SharedMemory(create=True, name="test", size=a.nbytes)
# Now create a NumPy array backed by shared memory
b = np.ndarray(a.shape, dtype=a.dtype, buffer=shm.buf)

In [23]:
b[2] = 3

In [9]:


existing_shm = shared_memory.SharedMemory(name='test')
c = np.ndarray(a.shape, a.dtype, buffer=existing_shm.buf)


In [27]:
c

array([0, 0, 3, 0, 0, 0])

In [13]:
d = np.zeros(a.shape)

In [25]:
d

array([0., 0., 2., 0., 0., 0.])

In [21]:
d[:] = c[:]

In [26]:
d

array([0., 0., 2., 0., 0., 0.])